[supervisord]
nodaemon=true
logfile=/tmp/supervisord.log
pidfile=/tmp/supervisord.pid

[program:datawarehouse]
command=python3 -m uvicorn datawarehouse.main:app --host 0.0.0.0 --port 8004
directory=/app/datawarehouse/src
environment=PYTHONPATH="/app/datawarehouse/src"
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/tmp/datawarehouse.out.log
stderr_logfile=/tmp/datawarehouse.err.log
